### ISSUE TITLE
FYI: upstream have ported to python3

### ISSUE THREAD

**Issue by JedMeister** [runfalk/storm-legacy#2]
I was researching python ORMs and came across this legacy fork, however, I also noticed that as of [v0.21](https://launchpad.net/storm/trunk/0.21) (latest is [v0.22](https://launchpad.net/storm/trunk/0.22)) upstream [supports py3](https://bugs.launchpad.net/storm/+bug/1530734).

Just figured I'd let you know...

**Comment by runfalk** [comment]
Thank you for letting me know! I've actually already put a note about it in the README.

> On September 20th, 2019 version 0.21 of Storm was released. The main differences seems to be that more features remain and that the exception handling was fixed propery for Python 3. In my fork it is not really possible to backend-agnostically catch exceptions.

I'm still on the fence whether I'll switch back to upstream Storm personally.

**Comment by JedMeister** [comment]
> I've actually already put a note about it in the README.

Oops, sorry for the noise... Good luck with it.
